ktor:
  application:
    modules:
      - dev.luketarr.ApplicationKt.module

    redis:
      port: $REDIS_PORT
      host: $REDIS_HOST
      username: $REDIS_USERNAME
      password: $REDIS_PASSWORD

  deployment:
    port: 8080
